### ISSUE TITLE
Collaborating on GraphQL syntax highlighter

### ISSUE THREAD

**Issue by asiandrummer** [gandm/language-graphql-lb#2]
Hey @gandm! I sent you an email regarding collaborating on the syntax highlighter with @rmosolgo a while back - I just tried sending you another email to the same email address but failed, so I'm trying to reach you via Github issues. Is there another email address I can use? We can definitely chat here if you prefer this channel :D

**Comment by rmosolgo** [comment]
:wave: Hey @gandm! I "grabbed" `language-graphql` early on, but as you can see, I haven't been able to do a good job with it. I'm really impressed by your work on this! I couldn't quite get the disambiguation between schema language and query language to work properly. 

Would you like to publish this project as `langauge-graphql`? I'm happy to do whatever is necessary to make that happen. I'm looking for some way to "add a collaborator" or something, but I'm coming up empty. Do either of you know how to hand off a project like this?

**Comment by gandm** [comment]
@asiandrummer yeah I deleted that email address. Just add any comments here for the time being - see remainder of this response.

@rmosolgo I'm happy to pass off this code to you if you want. I also noticed that @kumarharsh has also taken my grammar and used it for a [vscode graphql package](https://github.com/kumarharsh/graphql-for-vscode/blob/master/client/CHANGELOG.md), so maybe this needs some cross development between interested parties? I guess the easiest way forward would be for you to just take the code in this repo as yours and then you add collaborators to your repo as you see fit. I can then deprecate this package. Let me know your thoughts.

**Comment by asiandrummer** [comment]
@gandm thanks so much for being flexible with collaborations. To be honest, as someone inexperienced around the open source community, I become easily worried of working with people ;)

@kumarharsh hi there! I took a look at your vscode graphql package and it looks amazing! It's a long term plan, but I plan to extend the graphql language service I'm working to support Nuclide to vscode sometime early-mid next year. We should definitely talk :D 

@rmosolgo and everyone, let me know what/how I can help!

**Comment by kumarharsh** [comment]
@gandm you've done some great work on the syntax 👍 

@asiandrummer internally we already have a better support for Graphql including autocomplete, goto-definitions, etc. We're close to publishing it for the public - expect it in the coming weeks. I'd love to hear your thoughts. Please feel free to open issues on the [plugin's repo](https://github.com/kumarharsh/graphql-for-vscode) to post ideas, suggestions or bugs.

**Comment by kumarharsh** [comment]
@asiandrummer just fyi, the new features you mentioned landed last month in the `graphql-for-vscode` plugin. If you have some time, check them out.
